---
driver:
  name: digitalocean
  # Clamd will fail to start on some distros with only 512MB
  size: 1gb
platforms:
  - name: ubuntu-14-04-x64
  - name: ubuntu-12-04-x64
  - name: centos-6-5-x64
  - name: centos-5-10-x64
