language: ruby

branches:
  only:
    - master

sudo: required

services:
  - docker

cache:
  directories:
    - test/fixtures/cookbooks/clamav_test/files

env:
  global:
    - CVD_PATH=test/fixtures/cookbooks/clamav_test/files
  matrix:
    - SUITE=default PLATFORM=ubuntu
    - SUITE=enabled PLATFORM=ubuntu
    - SUITE=remove PLATFORM=ubuntu

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development

before_script:
  - mkdir -p $CVD_PATH
  - "[ -e $CVD_PATH/main.cvd ] || wget -P $CVD_PATH http://database.clamav.net/main.cvd"

script:
  - chef exec rake && chef exec kitchen test $SUITE-$PLATFORM
